name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: ['5.0.x']
        include:
          - os: windows-latest
            rid: win-x64
            zip: windows.zip
          - os: ubuntu-latest
            rid: linux-x64
            zip: linux.zip
          - os: macos-latest
            rid: osx-x64
            zip: macos.zip
          - os: macos-latest
            rid: osx-arm64
            zip: macos-arm64.zip

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.100-preview.4.21255.9'
        enable-prerelease: true
    
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -o ./publish/${{ matrix.rid }}

    - name: Zip the publish directory
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          Compress-Archive -Path ./publish/${{ matrix.rid }} -DestinationPath ${{ matrix.zip }}
        else
          zip -r ${{ matrix.zip }} ./publish/${{ matrix.rid }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.zip }}
        path: ./${{ matrix.zip }}